import React, { Fragment } from "react";
import { Link } from "react-router-dom";
import MetaData from "../layout/MetaData";
const Sales_executive_client_acquisition = () => {
    return (
        <Fragment>
            <MetaData title={'Sales Executive Client Acquisition'} />
            <Fragment>
                <main id="main">
                    {/* <!-- ======= Breadcrumbs ======= --> */}
                    <section id="breadcrumbs" className="breadcrumbs">
                        <div className="container">
                            <div className="d-flex justify-content-between align-items-center">
                                <h2></h2>
                                <ol><span className="ri-home-4-line">&nbsp; </span>
                                    <li><Link to="index.html">Home </Link></li>
                                    <li><Link to="Career.html">Career</Link></li>
                                    <li><Link to="sales-executive-client-acquisition.html"><u>Sales Executive Client Acquisition</u></Link></li>
                                </ol>
                            </div>
                        </div>
                    </section>
                    {/* <!-- about  --> */}
                    <section ><br />
                        <div className="container" data-aos="fade-up">
                            <img className="mt--45" src="assets/img/career.png" alt="career" /><br /><br />
                            <table className="table table-bordered">
                                <tr>
                                    <th width="27%"><h5> Post : </h5></th>
                                    <th><h3>Sales Executive Client Acquisition</h3></th>
                                </tr>
                                <tr>
                                    <td><h5>Reporting to :</h5></td>
                                    <td> Branch Manager</td>
                                </tr>
                                <tr>
                                    <td>
                                        <h5>Locations : </h5></td>
                                    <td>Pune</td>
                                </tr>
                                <tr>
                                    <td>
                                        <h5>Job Summary:</h5></td>
                                    <td> The profile requires leading a group of sales representatives. Acquire new customers on a regular basis by selling the e-commerce concept & leveraging relationships with them
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <h5>Experience:</h5></td>
                                    <td> 2-5 yrs experience in sales with min 1+ years experience in handling a team.
                                    </td>
                                </tr>
                                <tr><td><h5>Job Profile:</h5></td>
                                    <td> <h6>Key Responsibility Areas:</h6>
                                        <ul>
                                            <li ><i className=""></i>This role is primarily responsible for acquisition of new customers</li>
                                            <li><i className=""></i>Ensure that daily meeting targets of the team are met</li>
                                            <li><i className=""></i>Ensuring that the Team Sales Targets are met by ensuring the closure of the leads  generated by them</li>
                                            <li><i className=""></i>Ensure 100% compliance of the Sales Process</li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td><h5>Desired Profile:</h5></td>
                                    <td><h6>Qualification:</h6>
                                        <ul>
                                            <li ><i className=""></i>MBA/ B.Tech or Graduates with minimum relevant Sales Experience</li>
                                            <li ><i className=""></i>
                                                Male/Female with solid experience in SaaS Talent Acquisition Product of proven work experience as an Account Manager, Key Account Manager, Sales Account Manager, or relevant role</li>
                                            <li ><i className=""></i>Excellent listening, negotiation, and presentation abilities</li>
                                            <li ><i className=""></i>Strong verbal/written communication skills</li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr><td>
                                    <h5>Required Skills : </h5> </td>
                                    <td> <ul>
                                        <li ><i className=""></i>Should have flair towards sales.</li>
                                        <li ><i className=""></i>Should have a pleasing personality.</li>
                                        <li ><i className=""></i>Should have good written and verbal communication skills.</li>
                                        <li ><i className=""></i>Similar industry candidate will be given preference.</li>
                                        <li ><i className=""></i>Must have Team handling experience.</li>
                                    </ul> </td>
                                </tr>
                                <tr><td><h5>Mandatory:</h5></td>
                                    <td> Bike &#38; Laptop</td> </tr>
                            </table>
                        </div>
                    </section>
                    <div className="container" data-aos="fade-up">
                    </div>
                    {/* <!-- ======= Career Section ======= --> */}
                    <section id="blog" className="blog mt--75">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-8 entries">
                                    <div className="blog-comments" data-aos="fade-up">
                                        <div className="reply-form text-white">
                                            <h4>Career Form</h4>
                                            <p className="para">Your application will not be sent. Required fields are marked * </p>
                                            <form name="myform" method="post" onsubmit="validateCaptcha()">
                                                <div className="row">
                                                    <div className="col-md-6 form-group formGroup">
                                                        <input name="Name" id="Name" type="text" className="form-control" placeholder="Your Name*" />
                                                    </div>
                                                    <div className="col-md-6 form-group formGroup">
                                                        <input name="Email" id="Email" type="text" className="form-control" placeholder="Your Email*" />
                                                    </div>
                                                </div>
                                                <div className="row">
                                                    <div className="col form-group formGroup">
                                                        <input name="Mobile" id="Mobile" type="text" className="form-control" placeholder="Your Mobile Number*" />
                                                    </div>
                                                </div>
                                                <div className="row">
                                                    <div className="col form-group formGroup">
                                                        <input name="Post" id="Post" type="text" className="form-control" value="Sales Executive Client Acquisition " placeholder="Sales Executive Client Acquisition " readonly />
                                                    </div>
                                                </div>
                                                <div className="row">
                                                    <div className="col form-group formGroup" >
                                                        <label>Attach your Resume</label>
                                                        <input name="file1" id="file1" type="file" style={{padding: "3px"}} className="form-control" />
                                                    </div>
                                                </div>

                                                <div className="row">
                                                    <div className="col form-group formGroup">
                                                        <div id="captcha"></div>
                                                    </div>
                                                </div>

                                                <div className="row">
                                                    <div className="col form-group formGroup">
                                                        <label>Security Code*</label>
                                                        <input type="text" placeholder="Captcha" className="form-control" id="cpatchaTextBox" />
                                                    </div>
                                                </div>

                                                <div className="row">
                                                    <div className="col form-group formGroup">
                                                        <button type="submit" className="btn btn-danger">Submit</button>

                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </main>
            </Fragment>
        </Fragment>
    )
}

export default Sales_executive_client_acquisition

